DirectoryPath: "public"
CheckExternal: false
CheckInternal: true
EnforceHTTPS: false
IgnoreURLs:
  - "https://fonts.googleapis.com"
  - "https://fonts.gstatic.com"
  - "https://github.com"
  - "https://golang.org"
  - "https://ollama.ai"
